package createrecorder.handlers;

import java.io.File;
import java.io.FileInputStream;
import java.util.List;

import org.eclipse.core.commands.ExecutionEvent;
import org.eclipse.core.commands.ExecutionException;
import org.eclipse.core.resources.IFolder;
import org.eclipse.core.resources.IProject;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.Platform;
import org.eclipse.core.runtime.preferences.IPreferencesService;
import org.eclipse.jdt.core.ICompilationUnit;
import org.eclipse.jdt.core.IJavaProject;
import org.eclipse.jdt.core.IPackageFragment;
import org.eclipse.jdt.core.IPackageFragmentRoot;
import org.eclipse.jdt.core.JavaCore;
import org.eclipse.jface.dialogs.MessageDialog;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.ui.IWorkbenchWindow;
import org.eclipse.ui.handlers.HandlerUtil;

import com.androidApp.emitter.EmitRobotiumCodeBinary;
import com.androidApp.emitter.EmitRobotiumCodeSource;
import com.androidApp.emitter.EmitRobotiumCodeSource.LineAndTokens;
import com.androidApp.parser.ManifestParser;
import com.androidApp.parser.ProjectParser;
import com.androidApp.parser.ProjectPropertiesScan;
import com.androidApp.util.Constants;
import com.androidApp.util.FileUtility;

import createrecorder.util.EclipseUtility;
import createrecorder.util.Exec;
import createrecorder.util.ManifestInformation;
import createrecorder.util.PackageUtils;
import createrecorder.util.RecorderConstants;
import createrecorder.util.TestClassDialog;
import createrecorderplugin.popup.actions.GenerateRobotiumTestCode;

public class CreateTestHandler {
	public Object execute(ExecutionEvent event) throws ExecutionException {
		IWorkbenchWindow window = HandlerUtil.getActiveWorkbenchWindowChecked(event);
		Shell shell = window.getShell();
		String packagePath = TestClassDialog.getTestClassDialog(shell, "Robotium Recorder", "Enter classpath of APK to test");
		IPreferencesService service = Platform.getPreferencesService();
		String androidSDK = service.getString(RecorderConstants.ECLIPSE_ADT, RecorderConstants.ANDROID_SDK, null, null);
		String aaptPath = androidSDK + File.separator + Constants.Dirs.PLATFORM_TOOLS + File.separator + Constants.Executables.AAPT;
		String[] manifestLines = Exec.getShellCommandOutput(aaptPath + " dump --values xmltree " + PackageUtils.getPackageName(packagePath) + " AndroidManifest.xml");
		ManifestInformation manifestInformation = new ManifestInformation(manifestLines);
		if (!manifestInformation.verify()) {
			MessageDialog.openInformation(
					shell,
					"CreateRecorderPlugin",
					"failed to parse AndroidManifest.xml " + manifestInformation.errorMessage());
		} else {
			createProject(shell, manifestInformation);
		}
		return null;
	}
	
	public void createProject(Shell shell, ManifestInformation manifestInformation) {
		String eventsFileName = Constants.Names.DEVICE;
		String outputCodeFileName = Constants.Filenames.OUTPUT;
		try {
			IPreferencesService service = Platform.getPreferencesService();
			String androidSDK = service.getString(RecorderConstants.ECLIPSE_ADT, RecorderConstants.ANDROID_SDK, null, null);
			String projectName = manifestInformation.mApplicationName;

			// create the new project
			String newProjectName = projectName + Constants.Extensions.TEST;
			IProject testProject = EclipseUtility.createBaseProject(newProjectName);
			EmitRobotiumCodeBinary emitter = new EmitRobotiumCodeBinary();
			eventsFileName = GenerateRobotiumTestCode.getEventsFile(androidSDK, Constants.Names.DEVICE);
			List<LineAndTokens> lines = EmitRobotiumCodeSource.generateTestCode(emitter, eventsFileName);
			
			// test class path and test class name generated by emitter.
			String testClassPath = emitter.getApplicationClassPath() + Constants.Extensions.TEST;
			String testClassName = emitter.getApplicationClassName() + Constants.Extensions.TEST;
			String templateFileName = testClassName + "." + Constants.Extensions.JAVA;
			String packagePath = manifestInformation.mPackage +  Constants.Extensions.TEST;
			
			// scan to see if there are any unit tests in the source folder, and if not, the robotium jar file
			// hasn't been selected, so we have to prompt the user.
			IFolder srcFolder = testProject.getFolder(Constants.Dirs.SRC);
			int uniqueFileIndex = 0;
			if (srcFolder.exists()) {
				IFolder projectFolder = srcFolder.getFolder(FileUtility.sourceDirectoryFromClassName(packagePath));
				uniqueFileIndex = EclipseUtility.uniqueFileIndex(projectFolder, templateFileName);
			}
			if (uniqueFileIndex != 0) {
				testClassPath += Integer.toString(uniqueFileIndex);
				testClassName += Integer.toString(uniqueFileIndex) ;
			} else {

				// create the java project and write the test driver out into it
				IJavaProject javaProject = EclipseUtility.createJavaNature(testProject);
				GenerateRobotiumTestCode.createFolders(testProject);
				String target = "target=android-" + Integer.toString(manifestInformation.mTargetSDKVersion);
				GenerateRobotiumTestCode.createProjectProperties(testProject, target, manifestInformation.mApplicationName);
				GenerateRobotiumTestCode.createProject(testProject, manifestInformation.mApplicationName);

				// FIRST TIME ONLY:create the buil.xml AndroidManifest.xml, and resource files.
				GenerateRobotiumTestCode.writeBuildXML(testProject, emitter.getApplicationClassPath());
				GenerateRobotiumTestCode.writeManifest(testProject, testClassName, testClassPath, emitter.getApplicationPackage());
				GenerateRobotiumTestCode.writeResources(testProject);				
				GenerateRobotiumTestCode.writeClasspath(testProject,  manifestInformation.mApplicationName, Constants.Filenames.ROBOTIUM_JAR);
				GenerateRobotiumTestCode.copyJarToLibs(testProject, Constants.Filenames.UTILITY_JAR);
				GenerateRobotiumTestCode.copyJarToLibs(testProject, Constants.Filenames.ROBOTIUM_JAR);

				// create the package for the test code, then write the AllTests.java driver which executes all of the unit tests
				IPackageFragment pack = javaProject.getPackageFragmentRoot(srcFolder).createPackageFragment(packagePath, false, null);
				pack.open(null);
				GenerateRobotiumTestCode.copyTestDriverFile(pack, packagePath, emitter.getApplicationClassPath());
				pack.close();
			}
			// write out the test code, first to a temporary file, then to the actual project file.
			GenerateRobotiumTestCode.writeTestCode(emitter, lines, packagePath, testClassName, outputCodeFileName);
			IJavaProject javaProject = JavaCore.create(testProject);
			IPackageFragmentRoot packRoot = javaProject.getPackageFragmentRoot(srcFolder);
			packRoot.open(null);
			IPackageFragment pack = packRoot.getPackageFragment(packagePath);
			String testCode = FileUtility.readToString(new FileInputStream(outputCodeFileName));
			String projectFileOutput = testClassName + "." + Constants.Extensions.JAVA;
			ICompilationUnit classFile = pack.createCompilationUnit(projectFileOutput, testCode, true, null);	
			packRoot.close();
		} catch (Exception ex) {
			MessageDialog.openInformation(
					shell,
					"GenerateRobotiumTestCode",
					"There was an exception creating the test project " + ex.getMessage());
			ex.printStackTrace();
		}
	}
}
